session_name: dev
environment:
  TERM: xterm-256color
  LC_COLLATE: C
windows:
  - window_name: home
    window_index: 1
    layout: even-horizontal
    panes:
      - shell_command: TERM=xterm-256color; config status
        start_directory: ~/
      - shell_command: ls
        start_directory: ~/dev
        focus: true
  - window_name: dev
    window_index: 2
    start_directory: ~/dev
    layout: even-horizontal
    panes:
      -
      -
